apiVersion: v2
name: mojito
description: Mojito is a continuous localization platform.
home: https://github.com/box/mojito
icon: https://raw.githubusercontent.com/box/mojito/master/docs/images/logo.png
type: application
version: 0.1.0
appVersion: 0.111-SNAPSHOT
keywords:
  - mojito
  - translation
  - localization
  - i18n
  - l10n
sources:
  - https://github.com/box/mojito
dependencies:
- name: mysql-operator
  version: "2.2.7"
  repository: "https://mysql.github.io/mysql-operator/"
  condition: mysql.enabled
maintainers:
- name: Mojito Team
  url: https://github.com/box/mojito
