{{- if .Values.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mojito.fullname" . }}-api-config
  labels:
    {{- include "mojito.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  application.json: |
    {{- include "mojito.springApplicationJson" . | nindent 4 }}
{{- end }}
