{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mojito.fullname" . }}-mysql
  labels:
    {{- include "mojito.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
