{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mojito.fullname" . }}-mysql
  labels:
    {{- include "mojito.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "mojito.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
