{{- if and .Values.mysql.operator.enabled .Values.mysql.cluster.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.cluster.secretName }}
  labels:
    {{- include "mojito.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.mysql.auth.rootUser | quote }}
  rootHost: "%"
  rootPassword: {{ .Values.mysql.auth.rootPassword | quote }}
{{- end }}
